name: UX Review

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  uxReview:
    if: github.event.label.name == 'ux review'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: >
            🧐 UX Reviewers Assemble!
              - @cepedavanessa
              - @conor-darcy
              - @gemma-moore10
              - @JackieYada
              - @MonseGarciaLimon
              - @stephenim
              - @VirtualClover

            **Review Reminders**
              1. Add a comment to let us know who is reviewing this change
              2. Check out the implementation @ https://apps.inindca.com/common-ui-docs/genesys-webcomponents/${{ github.head_ref }}
              3. Be sure to note which issues are blockers and which are refinements
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
